name: laps
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.13.*
  - pytorch=2.7
  - numpy
  - h5py
  - black
  - matplotlib
  - pip
  - einops
  - pre-commit
  - tqdm
  - wandb
  - pandas
  - ipykernel
  - loguru
  - accelerate=1.7.0
  - pytest
  - tyro
  - datasets
  - transformers=4.52.4
  - nibabel
  - mat73
  - torchvision
  - antspyx
  - tensorboard
  - huggingface_hub
  - monai
  - nvitop
  - pip:
    - git+https://github.com/mikgroup/sigpy.git@5f63aa5cb3646023a00e83ea708e767861271b94
    - opencv-python
    - cupy-cuda12x
    - polars
    - pyeyes
    - -e submodules/diffusers
    - -e submodules/laps-medvae
    - -e .
